name: format code

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  format_through_push:
    name: format, add, commit, push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.email "ematsuo93@gmail.com"
          git config --global user.name "ItisErina"
      - name: Install packages
        run: yarn install
      - name: Set information to github
        run: git remote set-url origin https://github.com/${{ github.repository }}.git
      - name: Format code
        run: yarn run format
      - name: Check status
        run: git status
      - name: Stage changes
        run: git diff --quiet && git diff --staged --quiet || git add .
      - name: Commit changes
        run: git diff --quiet && git diff --staged --quiet || git commit -m "Format code automatically"
      - name: Push changes
        run: git push origin HEAD:$(git symbolic-ref --short HEAD)
