name: format code

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  format_through_push:
    name: format, add, commit, push
    runs-on: ubuntu-latest
    env:
      MY_PAT: ${{ secrets.MY_PAT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install packages
        run: yarn install
      - name: Set information to github 
        run: |
          git remote set-url origin https://${GITHUB_ACTOR}:${MY_PAT}@github.com/${GITHUB_REPOSITORY}
      - name: Checkout pushed branch
        run: |
          git fetch
          git branch
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          git checkout $BRANCH_NAME
      - name: Format code
        run: yarn run format
      - name: Check status
        run: git status
      - name: Add changes
        run: git add .
      - name: Commit changes
        run: git commit -m "Auto commit from GitHub Actions"
      - name: Push to github
        run: git push --set-upstream origin $BRANCH_NAME
